name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [14, 8]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2.3.1
      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v1.3.0
        with:
          java-version: ${{ matrix.java }}
      - name: Build
        run: ./gradlew build test
